# The following redirect is intended for use with most SPAs that handle
# routing internally.

[[redirects]]
  from = "/api/*"
  to = "https://api-endpoint.ejemplo.com.ar/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
